
networks:
  ad-test-net:
    external: true

  server:
    image: ghcr.io/bitnoize/ad-test-server:latest
    environment:
      - UID=4020
      - GID=4020
      - APP_CONFIG_SCHEMA=${APP_CONFIG_SCHEMA}
      - APP_CONFIG=${APP_CONFIG}
    networks:
      - ad-test-net
    depends_on:
      - connect-redis
      - connect-proxy-http
    restart: unless-stopped

  connect-redis:
    image: alpine/socat
    networks:
      - ad-test-net
    restart: unless-stopped
    deploy:
      mode: global

  connect-proxy-http:
    image: alpine/socat
    networks:
      - ad-test-net
    restart: unless-stopped
    deploy:
      mode: global

